---
AWSTemplateFormatVersion: 2010-09-09
Description: eks user

Resources:

  EksUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      UserName: eks
      Policies:
        - PolicyName: eks-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - "eks:*"
              - "ec2:DescribeInstances"
              - "eks:DescribeCluster"
              Resource: '*'

  EksUserCredentials:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref EksUser

  BotCredentialsStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /bot/credentials/${EksUser}
      SecretString: !Sub '{"ACCESS_KEY":"${EksUserCredentials}","SECRET_KEY":"${EksUserCredentials.SecretAccessKey}"}'
Outputs:
  AccessKeyID:
    Value: !Ref EksUserCredentials
  SecretAccessKey:
    Value: !GetAtt EksUserCredentials.SecretAccessKey
  User:
    Value: !Ref EksUser